######################################################################
# Automatically generated by qmake (3.0) Sat Aug 2 13:21:10 2014
######################################################################

TEMPLATE = app
TARGET = tcs
INCLUDEPATH += . peripheral

# Input
HEADERS += base.hpp peripheral/peripheral.hpp
SOURCES += base.cpp main.cpp peripheral/peripheral.cpp
